//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CW_FileCompressor.Properties.Langs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lang() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CW_FileCompressor.Properties.Langs.Lang", typeof(Lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string AboutLabel {
            get {
                return ResourceManager.GetString("AboutLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The account with the same email address exists!.
        /// </summary>
        public static string AccountExistsLabel {
            get {
                return ResourceManager.GetString("AccountExistsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization.
        /// </summary>
        public static string AuthorizationLabel {
            get {
                return ResourceManager.GetString("AuthorizationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BackLabel {
            get {
                return ResourceManager.GetString("BackLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string ButtonLogInContent {
            get {
                return ResourceManager.GetString("ButtonLogInContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        public static string ButtonSignUpContent {
            get {
                return ResourceManager.GetString("ButtonSignUpContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelLabel {
            get {
                return ResourceManager.GetString("CancelLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find account with your values!.
        /// </summary>
        public static string CannotFindAccountLabel {
            get {
                return ResourceManager.GetString("CannotFindAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read the file: {0}.
        /// </summary>
        public static string CannotReadFileLabel {
            get {
                return ResourceManager.GetString("CannotReadFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress file.
        /// </summary>
        public static string CompressFileLabel {
            get {
                return ResourceManager.GetString("CompressFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression Method.
        /// </summary>
        public static string CompressionMethodLabel {
            get {
                return ResourceManager.GetString("CompressionMethodLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress.
        /// </summary>
        public static string CompressLabel {
            get {
                return ResourceManager.GetString("CompressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress file.
        /// </summary>
        public static string DecompressFileLabel {
            get {
                return ResourceManager.GetString("DecompressFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decompress.
        /// </summary>
        public static string DecompressLabel {
            get {
                return ResourceManager.GetString("DecompressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop.
        /// </summary>
        public static string DesktopLabel {
            get {
                return ResourceManager.GetString("DesktopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Disk (C:).
        /// </summary>
        public static string DiskCLabel {
            get {
                return ResourceManager.GetString("DiskCLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Disk (D:).
        /// </summary>
        public static string DiskDLabel {
            get {
                return ResourceManager.GetString("DiskDLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Disk (E:).
        /// </summary>
        public static string DiskELabel {
            get {
                return ResourceManager.GetString("DiskELabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disks.
        /// </summary>
        public static string DisksLabel {
            get {
                return ResourceManager.GetString("DisksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string DocumentsLabel {
            get {
                return ResourceManager.GetString("DocumentsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string DoneLabel {
            get {
                return ResourceManager.GetString("DoneLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloads.
        /// </summary>
        public static string DownloadsLabel {
            get {
                return ResourceManager.GetString("DownloadsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Element(s): {0}.
        /// </summary>
        public static string ElementsLabel {
            get {
                return ResourceManager.GetString("ElementsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter email.
        /// </summary>
        public static string EmailHint {
            get {
                return ResourceManager.GetString("EmailHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field should have at least 5 symbols and some specials (@, .)..
        /// </summary>
        public static string EmailToolTip {
            get {
                return ResourceManager.GetString("EmailToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error has occured.
        /// </summary>
        public static string ErrorOccuredLabel {
            get {
                return ResourceManager.GetString("ErrorOccuredLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File compressor.
        /// </summary>
        public static string FileCompressor {
            get {
                return ResourceManager.GetString("FileCompressor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path.
        /// </summary>
        public static string FilePathLabel {
            get {
                return ResourceManager.GetString("FilePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size: {0} bytes.
        /// </summary>
        public static string FileSizeLabel {
            get {
                return ResourceManager.GetString("FileSizeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string FoldersLabel {
            get {
                return ResourceManager.GetString("FoldersLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string LangEnglish {
            get {
                return ResourceManager.GetString("LangEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageLabel {
            get {
                return ResourceManager.GetString("LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukrainian.
        /// </summary>
        public static string LangUkrainian {
            get {
                return ResourceManager.GetString("LangUkrainian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LoginLabel {
            get {
                return ResourceManager.GetString("LoginLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Music.
        /// </summary>
        public static string MusicLabel {
            get {
                return ResourceManager.GetString("MusicLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot identify compression algorithm!.
        /// </summary>
        public static string NoAlgorithmLabel {
            get {
                return ResourceManager.GetString("NoAlgorithmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory cannot be found: {0}.
        /// </summary>
        public static string NoDirLabel {
            get {
                return ResourceManager.GetString("NoDirLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file cannot be found: {0}.
        /// </summary>
        public static string NoFileFoundLabel {
            get {
                return ResourceManager.GetString("NoFileFoundLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to select an item!.
        /// </summary>
        public static string NoSelectedItemLabel {
            get {
                return ResourceManager.GetString("NoSelectedItemLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string OkLabel {
            get {
                return ResourceManager.GetString("OkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter password.
        /// </summary>
        public static string PasswordHint {
            get {
                return ResourceManager.GetString("PasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field should have at least 8 characters..
        /// </summary>
        public static string PasswordToolTip {
            get {
                return ResourceManager.GetString("PasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        public static string PicturesLabel {
            get {
                return ResourceManager.GetString("PicturesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        public static string RegistartionLabel {
            get {
                return ResourceManager.GetString("RegistartionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat password.
        /// </summary>
        public static string RepeatPasswordHint {
            get {
                return ResourceManager.GetString("RepeatPasswordHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field should be equal to password field value..
        /// </summary>
        public static string RepeatPasswordToolTip {
            get {
                return ResourceManager.GetString("RepeatPasswordToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file path.
        /// </summary>
        public static string SaveFilePathLabel {
            get {
                return ResourceManager.GetString("SaveFilePathLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAUTION! All settings apply after app restart..
        /// </summary>
        public static string SaveSettingsCautionLabel {
            get {
                return ResourceManager.GetString("SaveSettingsCautionLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string SelectLabel {
            get {
                return ResourceManager.GetString("SelectLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string SettingsLabel {
            get {
                return ResourceManager.GetString("SettingsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been compressed!.
        /// </summary>
        public static string SuccessCompressLabel {
            get {
                return ResourceManager.GetString("SuccessCompressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file has been decompressed!.
        /// </summary>
        public static string SuccessDecompressLabel {
            get {
                return ResourceManager.GetString("SuccessDecompressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string ThemeLabel {
            get {
                return ResourceManager.GetString("ThemeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter username.
        /// </summary>
        public static string UsernameHint {
            get {
                return ResourceManager.GetString("UsernameHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field should have at least 1 character..
        /// </summary>
        public static string UsernameToolTip {
            get {
                return ResourceManager.GetString("UsernameToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Videos.
        /// </summary>
        public static string VideosLabel {
            get {
                return ResourceManager.GetString("VideosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing fields value or wrong input!.
        /// </summary>
        public static string WrongInputLabel {
            get {
                return ResourceManager.GetString("WrongInputLabel", resourceCulture);
            }
        }
    }
}
